//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Devices()
        {
            this.Stuff = new HashSet<Stuff>();
        }
    
        public int devAutoId { get; set; }
        public string devCode { get; set; }
        public string devType { get; set; }
        public string devApi { get; set; }
        public string devApiKey { get; set; }
        public string devLocation { get; set; }
        public string devIP { get; set; }
        public string devAdmin { get; set; }
        public string devPass { get; set; }
        public Nullable<int> devLayoutId { get; set; }
    
        public virtual DevLayout DevLayout { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stuff> Stuff { get; set; }
    }
}
