//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceIO
    {
        public string ioName { get; set; }
        public string ioType { get; set; }
        public string ioValType { get; set; }
        public string ioValue { get; set; }
        public Nullable<int> ioDevId { get; set; }
    }
}
