//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class LayoutSettings
    {
        public int ltSId { get; set; }
        public int ltSDevLayoutId { get; set; }
        public string ltSType { get; set; }
        public string ltSContent { get; set; }
        public string ltSValue { get; set; }
        public string ItSPosition { get; set; }
    
        public virtual DevLayout DevLayout { get; set; }
    }
}
